apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sync-harbor
spec:
  params:
    - name: inHarborUrl
      type: string
      default: "harbor.arfa.wise-paas.com"
    - name: isSyncImage
      type: string
      default: "true"
      description: "true or false"
    - name: inHarborImage
      type: string
      default: "null"
      description: "例如: ensaas_routers_backend/ensaas_routers_backend"
    - name: imageTag
      type: string
      default: "null"
    - name: outHarborUrl
      type: string
      default: "harbor.wise-paas.com,harbor.hz.wise-paas.com.cn"
    - name: outHarborImage
      type: string
      default: "null"
      description: "例如: ensaas-production/ensaas-router/backend"
    - name: isSyncChart
      type: string
      default: "true"
      description: "true or false"
    - name: chartName
      type: string
      default: "null"
    - name: chartVersion
      type: string
      default: "null"


  tasks:
    - name: sync-harbor-image
      taskRef:
        name: sync-harbor-image
      params:
        - name: outHarborUrl
          value: $(params.outHarborUrl)
        - name: isSyncImage
          value: $(params.isSyncImage)
        - name: inHarborUrl
          value: $(params.inHarborUrl)
        - name: inHarborImage
          value: $(params.inHarborImage)
        - name: imageTag
          value: $(params.imageTag)
        - name: outHarborImage
          value: $(params.outHarborImage)

    - name: sync-helm-chart
      taskRef:
        name: sync-helm-chart
      params:
        - name: outHarborUrl
          value: $(params.outHarborUrl)
        - name: isSyncChart
          value: $(params.isSyncChart)
        - name: inHarborUrl
          value: $(params.inHarborUrl)
        - name: inHarborImage
          value: $(params.inHarborImage)
        - name: outHarborImage
          value: $(params.outHarborImage)
        - name: chartName
          value: $(params.chartName)
        - name: chartVersion
          value: $(params.chartVersion)
