apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: uninstall-chart
spec:
  params:
    - name: namespace
      type: string
    - name: releaseName
      type: string
    - name: configName
      type: string
      description: Name of config map
  tasks:
    - name: uninstall-helm-chart
      taskRef:
        name: uninstall-helm-chart
      params:
        - name: namespace
          value: $(params.namespace)
        - name: releaseName
          value: $(params.releaseName)
        - name: configName
          value: $(params.configName)
