apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: uninstall-helm-chart
spec:
  inputs:
    params:
      - name: releaseName
        type: string
        default: myrelease
      - name: namespace
        type: string
      - name: configName
        type: string
        description: Name of config map
      - name: volumeName
        type: string
        description: Name of volume
        default: config

  steps:
    - name: install-helm-chart
      image: lachlanevenson/k8s-helm:v3.1.1
      script: |
        helm uninstall  $(inputs.params.releaseName) -n $(inputs.params.namespace)
      volumeMounts:
        - name: "$(inputs.params.volumeName)"
          mountPath: /tekton/home/.kube

  volumes:
    - name: "$(inputs.params.volumeName)"
      configMap:
        name: "$(inputs.params.configName)"
