apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: install-helm-chart
spec:
  inputs:
    params:
      - name: configName
        type: string
        description: Name of config map
      - name: volumeName
        type: string
        description: Name of volume
        default: config
      - name: releaseName
        type: string
        default: myrelease
      - name: chartName
        type: string
      - name: namespace
        type: string
      - name: repoName
        type: string
        default: harbor
      - name: repoUrl
        type: string
      - name: repoUsername
        type: string
      - name: repoPassword
        type: string

  steps:
    - name: install-helm-chart
      image: lachlanevenson/k8s-helm:v3.1.1
      script: |
        helm repo add --username $(inputs.params.repoUsername) --password $(inputs.params.repoPassword) $(inputs.params.repoName) $(inputs.params.repoUrl)
        helm install  $(inputs.params.helmName) $(inputs.params.repoName)/$(inputs.params.chartName) -n $(inputs.params.namespace)
        helm ls -n $(inputs.params.namespace)
      volumeMounts:
        - name: "$(inputs.params.volumeName)"
          mountPath: /tekton/home/.kube

  volumes:
    - name: "$(inputs.params.volumeName)"
      configMap:
        name: "$(inputs.params.configName)"
