apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: get-ingress
spec:
  inputs:
    params:
      - name: namespace
        type: string
      - name: releaseName
        type: string
      - name: chartName
        type: string
      - name: configName
        type: string
      - name: volumeName
        type: string
        default: config
  steps:
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      script: |
        kubectl get ingress -n $(inputs.params.namespace) |grep $(inputs.params.releaseName)-$(inputs.params.chartName)
      volumeMounts:
        - name: "$(inputs.params.volumeName)"
          mountPath: /tekton/home/.kube

  volumes:
    - name: "$(inputs.params.volumeName)"
      configMap:
        name: "$(inputs.params.configName)"
