FROM harbor.wise-paas.io/kaniko-project/executor:v0.15.0

FROM alpine

COPY --from=0 /kaniko/executor /kaniko/executor
COPY --from=0 /kaniko/ssl/certs/ /kaniko/ssl/certs/
ENV HOME /root
ENV USER /root
ENV PATH /bin:/usr/bin:/usr/local/bin
ENV SSL_CERT_DIR=/kaniko/ssl/certs

#ENTRYPOINT ["/kaniko/executor"]
CMD ["sh"]