FROM alpine

ADD helm /usr/local/bin
RUN apk add --update wget git openssl bash \&& helm plugin install https://github.com/chartmuseum/helm-push


RUN apk add --update ca-certificates \
 && apk add --update -t deps wget git openssl bash \
 && wget -q https://get.helm.sh/helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz \
 && tar -xf helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz \
 && mv linux-amd64/helm /usr/local/bin \
 && apk del --purge deps \
 && rm /var/cache/apk/* \
 && rm -f /helm-${HELM_LATEST_VERSION}-linux-amd64.tar.gz \
 && helm plugin install https://github.com/chartmuseum/helm-push

ENTRYPOINT ["helm"]
CMD ["help"]