apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: delete-pipelinerun
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: tekton-pipeline
          containers:
          - name: delete-pipelinerun
            image: core-harbor-devops-ali.wise-paas.com.cn/library/kubectl-delete-pipelinerun:1.0.2
            imagePullPolicy: IfNotPresent #Always
            command: ["sh"]
            args: ["/opt/delete-pipelinerun.sh","tekton-pipelines","\"2d\""]
          restartPolicy: OnFailure
