apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-image
spec:
  resources:
    - name: source-repo
      type: git
    - name: image-repo
      type: image
  params:
    - name: pathToDockerFile
      type: string
      default: Dockerfile
    - name: pathToContext
      type: string
      default: /
      description: dockerfile dir
    - name: imageTag
      type: string
      default: v-1.0.0
      description: Build docker image tag
  tasks:
    - name: build-docker-image-from-git-source 
      taskRef:
        name: build-docker-image-from-git-source 
      params:
        - name: pathToDockerFile
          value: $(params.pathToDockerFile)
        - name: pathToContext
          value: $(params.pathToContext)
        - name: imageTag
          value: $(params.imageTag)
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: image-repo

