apiVersion: v1
kind: Secret
metadata:
  name: docker-basic-user-pass
  annotations:
    tekton.dev/docker-0: https://harbor.arfa.wise-paas.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
