apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sync-harbor
spec:
  params:
    - name: inHarborUrl
      type: string
      default: "harbor.arfa.wise-paas.com"
    - name: inHarborImage
      type: string
      description: "例如: ensaas_routers_backend/ensaas_routers_backend"
    - name: imageTag
      type: string
    - name: outHarborUrl
      type: string
      default: "core-harbor-devops-ali.wise-paas.com.cn"
    - name: outHarborImage
      type: string
      description: "例如: ensaas-production/ensaas-router/backend"
    - name: chartName
      type: string
    - name: chartVersion
      type: string

  tasks:
    - name: sync-harbor-image
      taskRef:
        name: sync-harbor-image
      params:
        - name: inHarborUrl
          value: $(params.inHarborUrl)
        - name: inHarborImage
          value: $(params.inHarborImage)
        - name: imageTag
          value: $(params.imageTag)
        - name: outHarborUrl
          value: $(params.outHarborUrl)
        - name: outHarborImage
          value: $(params.outHarborImage)

    - name: sync-helm-chart
      taskRef:
        name: sync-helm-chart
      params:
        - name: inHarborUrl
          value: $(params.inHarborUrl)
        - name: inHarborImage
          value: $(params.inHarborImage)
        - name: outHarborUrl
          value: $(params.outHarborUrl)
        - name: outHarborImage
          value: $(params.outHarborImage)
        - name: chartName
          value: $(params.chartName)
        - name: chartVersion
          value: $(params.chartVersion)