apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: sync-helm-chart
spec:
  inputs:
    params:
      - name: inHarborUrl
        type: string
      - name: inHarborUsername
        type: string
      - name: inHarborPassword
        type: string
      - name: inProjectName
        type: string
      - name: inChartName
        type: string
      - name: inChartVersion
        type: string
      - name: outHarborUrl
        type: string
      - name: outHarborUsername
        type: string
      - name: outHarborPassword
        type: string
      - name: outProjectName
        type: string


  steps:
    - name: sync-harbor-chart
      image:  core-harbor-devops-ali.wise-paas.com.cn/library/k8s-helm:v3.1.1.1
      script: |
        helm repo add --username $(inputs.params.inHarborUsername) --password '$(inputs.params.inHarborPassword)' $(inputs.params.inProjectName) https://$(inputs.params.inHarborUrl)/chartrepo/$(inputs.params.inProjectName)
        helm repo add --username $(inputs.params.outHarborUsername) --password '$(inputs.params.outHarborPassword)' $(inputs.params.outProjectName) https://$(inputs.params.outHarborUrl)/chartrepo/$(inputs.params.outProjectName)
        helm pull --version $(inputs.params.inChartVersion) $(inputs.params.inProjectName)/$(inputs.params.inChartName)
        tar zxvf $(inputs.params.inChartName)-$(inputs.params.inChartVersion).tgz
        sed -i 's/Always/IfNotPresent/g' '$(inputs.params.inChartName)'/values.yaml
        sed -i 's/$(inputs.params.inHarborUrl)\/$(inputs.params.inProjectName)\/$(inputs.params.inChartName)/$(inputs.params.outHarborUrl)\/$(inputs.params.outProjectName)\/$(inputs.params.inProjectName)\/$(inputs.params.inChartName)/g'  $(inputs.params.inChartName)/values.yaml
        /opt/bin/helmpush $(inputs.params.inChartName) $(inputs.params.outProjectName)
