apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: sync-helm-chart
spec:
  inputs:
    params:
      - name: inHarborUrl
        type: string
      - name: inHarborImage
        type: string
      - name: outHarborUrl
        type: string
      - name: outHarborImage
        type: string
      - name: chartName
        type: string
      - name: chartVersion
        type: string


  steps:
    - name: sync-harbor-chart
      image:  core-harbor-devops-ali.wise-paas.com.cn/library/k8s-helm:v3.1.1.1
      env:
        - name: inHarborUsername
          valueFrom:
            secretKeyRef:
              name: docker
              key: username
        - name: inHarborPassword
          valueFrom:
            secretKeyRef:
              name: docker
              key: password
        - name: outHarborUsername
          valueFrom:
            secretKeyRef:
              name: docker-core
              key: username
        - name: outHarborPassword
          valueFrom:
            secretKeyRef:
              name: docker-core
              key: password
      script: |
        #!/usr/bin/env sh
        inImage=$(inputs.params.inHarborUrl)/$(inputs.params.inHarborImage)
        outImage=$(inputs.params.outHarborUrl)/$(inputs.params.outHarborImage)
        inProjectName=`echo $(inputs.params.inHarborImage)|awk -F '/' '{print $1}'`
        outProjectName=`echo $(inputs.params.outHarborImage)|awk -F '/' '{print $1}'`
        helm repo add --username $inHarborUsername --password $inHarborPassword $inProjectName https://$(inputs.params.inHarborUrl)/chartrepo/$inProjectName
        helm repo add --username $outHarborUsername --password $outHarborPassword $outProjectName https://$(inputs.params.outHarborUrl)/chartrepo/$outProjectName
        helm pull --version $(inputs.params.chartVersion) $inProjectName/$(inputs.params.chartName)
        tar zxvf $(inputs.params.chartName)-$(inputs.params.chartVersion).tgz
        sed -i 's/Always/IfNotPresent/g' $(inputs.params.chartName)/values.yaml
        sed -i 's#'$inImage'#'$outImage'#g'  $(inputs.params.chartName)/values.yaml
        /opt/bin/helmpush $(inputs.params.chartName) $outProjectName
