apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sync-harbor
spec:
  params:
    - name: inHarborUrl
      type: string
      description: 源harbor地址
    - name: inHarborUsername
      type: string
      description: 源harbor用户
    - name: inHarborPassword
      type: string
      description: 源harbor密码
    - name: inProjectName
      type: string
      description: 源harbor镜像所在项目
    - name: inImageName
      type: string
      description: 镜像名称
    - name: inImageVersion
      type: string
    - name: inChartName
      type: string
      description: chart名称
    - name: inChartVersion
      type: string
    - name: outHarborUrl
      type: string
    - name: outHarborUsername
      type: string
    - name: outHarborPassword
      type: string
    - name: outProjectName
      type: string
      description: 目标harbor项目名称 (app-production、ensaas-production、ensaas-shared)
    - name: outImageProject
      type: string
      description: 目标harbor二级项目名称

  tasks:
    - name: sync-harbor-image
      taskRef:
        name: sync-harbor-image
      params:
        - name: inHarborUrl
          value: $(params.inHarborUrl)
        - name: inHarborUsername
          value: $(params.inHarborUsername)
        - name: inHarborPassword
          value: $(params.inHarborPassword)
        - name: inProjectName
          value: $(params.inProjectName)
        - name: inImageName
          value: $(params.inImageName)
        - name: inImageTag
          value: $(params.inImageVersion)
        - name: outHarborUrl
          value: $(params.outHarborUrl)
        - name: outHarborUsername
          value: $(params.outHarborUsername)
        - name: outHarborPassword
          value: $(params.outHarborPassword)
        - name: outProjectName
          value: $(params.outProjectName)
        - name: outImageProject
          value: $(params.outImageProject)

    - name: sync-helm-chart
      taskRef:
        name: sync-helm-chart
      runAfter:
        - sync-harbor-image
      params:
        - name: inHarborUrl
          value: $(params.inHarborUrl)
        - name: inHarborUsername
          value: $(params.inHarborUsername)
        - name: inHarborPassword
          value: $(params.inHarborPassword)
        - name: inProjectName
          value: $(params.inProjectName)
        - name: inChartName
          value: $(params.inChartName)
        - name: inChartVersion
          value: $(params.inChartVersion)
        - name: outHarborUrl
          value: $(params.outHarborUrl)
        - name: outHarborUsername
          value: $(params.outHarborUsername)
        - name: outHarborPassword
          value: $(params.outHarborPassword)
        - name: outProjectName
          value: $(params.outProjectName)
