apiVersion: v1
kind: Secret
metadata:
  name: gitlab
  annotations:
    tekton.dev/git-0: http://advgitlab.eastasia.cloudapp.azure.com
type: kubernetes.io/basic-auth
stringData:
  username: 
  password: 
