apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitlab-ci
spec:
  params:
    - name: gitProjectName
      description: The git project name
    - name: gitHttpUrl
      description: The git project http url
    - name: revision
      default: master
    - name: imageName
      description: image name
    - name: tagName
      description: The tag name
    - name: pathToDockerFile
      type: string
      default: Dockerfile
    - name: pathToContext
      type: string
      description: dockerfile dir
      default: "/"
    - name: harborUrl
      type: string


  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: gitlab-ci-$(uid)
      spec:
        serviceAccountName: tekton-pipeline
        pipelineRef:
          name: build-image-and-push-chart
        resources:
          - name: git-source
            resourceSpec:
              type: git
              params:
                - name: url
                  value: $(tt.params.gitHttpUrl)
                - name: revision
                  value: $(tt.params.revision)
          - name: image-source
            resourceSpec:
              type: image
              params:
                - name: url
                  value: $(tt.params.harborUrl)/$(tt.params.imageName)

        params:
          - name: gitProjectName
            value: $(tt.params.gitProjectName)
          - name: pathToDockerFile
            value: Dockerfile
          - name: pathToContext
            value:  $(tt.params.pathToContext)
          - name: tagName
            value: $(tt.params.tagName)
          - name: harborUrl
            value: $(tt.params.harborUrl)
