apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitlab-tag-push-binding
spec:
  params:
    - name: serviceAccountName  #kubectl create clusterrolebinding tekton-pipeline --clusterrole=cluster-admin --serviceaccount=tekton-pipelines:tekton-pipeline --namespace=tekton-pipelines 
      value: tekton-pipeline
    - name: gitProjectName
      value: $(body.project.name)
    - name: gitHttpUrl
      value: $(body.project.git_http_url)
    - name: revision
      value: $(body.project.default_branch)
    - name: tagName
      value: $(body.ref)
    - name: pathToDockerFile
      value: Dockerfile
    - name: pathToContext
      value: ""
    - name: harborUrl
      value: ""  # 不含https://
    - name: harborUsername
      value: "lu.jin@advantech.com.cn"
    - name: harborPassword
      value: ""

